version: "3.7"

services:
  db:
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    env_file:
      - ./.env


  web:
    build: ./backend
    environment:
      - DB_NAME=${SQL_DATABASE}
      - DB_USER=${SQL_USER}
      - DB_PASSWORD=${SQL_PASSWORD}
    env_file:
      - ./.env

    volumes:
      - ./backend:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ./wait-for-it.sh db:5432 -- ./entrypoint.sh

volumes:
  postgres_data:

# add setup.py to do https://docs.djangoproject.com/en/3.1/intro/tutorial02
# https://stackoverflow.com/questions/44785585/how-to-delete-all-local-docker-images
# https://docs.djangoproject.com/en/dev/topics/settings/#envvar-DJANGO_SETTINGS_MODULE
# https://stackoverflow.com/questions/34114427/django-upgrading-to-1-9-error-appregistrynotready-apps-arent-loaded-yet